baseURL                = 'https://jim00000.github.io/'
languageCode           = 'en'
languageName           = 'English'
defaultContentLanguage = 'en'
title                  = "Jim's Blogger"
theme                  = 'LoveIt'
copyright              = '© 2025 Jim00000.  All rights reserved.'
hasCJKLanguage         = true
enableRobotsTXT        = true
enableGitInfo          = true
enableEmoji            = true
ignoreErrors           = ['error-remote-getjson', 'error-missing-instagram-accesstoken']

[pagination]
    disableAliases = false
    pagerSize = 10
    path = "page"

[menu]
    [[menu.main]]
        weight = 1
        identifier = 'posts'
        pre = ''
        post = ''
        name = '文章'
        url = '/posts/'
        title = ''
    [[menu.main]]
        weight = 2
        identifier = 'tags'
        pre = ''
        post = ''
        name = '標籤'
        url = '/tags/'
        title = ''
    [[menu.main]]
        weight = 3
        identifier = 'categories'
        pre = ''
        post = ''
        name = '分類'
        url = '/categories/'
        title = ''

[params]
    defaultTheme = 'auto'
    gitRepo = 'https://github.com/Jim00000'
    fingerprint = ''
    dateFormat = '2006-01-02'
    title = ''
    description = ''
    images = []

    [params.author]
        name = 'Jim00000'
        email = ''
        link = ''

    [params.header]
        desktopMode = 'fixed'
        mobileMode = 'auto'

        [params.header.title]
            logo = ''
            name = "技術隨筆"
            pre = ''
            post = ''
            typeit = false

    [params.footer]
        enable = true
        custom = ''
        hugo = true
        copyright = true
        author = true
        since = 2025
        license = 'All rights reserved.'

    [params.home]
    rss = 10

        [params.home.profile]
            enable = true
            gravatarEmail = ''
            avatarURL = ''
            title = ''
            subtitle = 'It is never too late to learn'
            typeit = true
            social = true
            disclaimer = ''

        [params.home.posts]
            enable = true
            paginate = 6
    
    [params.social]
        GitHub = 'Jim00000'

    [params.section]
        paginate = 20
        dateFormat = "01-02"
        rss = 10

    [params.list]
        paginate = 20
        dateFormat = "01-02"
        rss = 10

    [params.app]
        title = "Jim's Blogger"
        noFavicon = false
        svgFavicon = ''
        themeColor = "#ffffff"
        iconColor = "#5bbad5"
        tileColor = "#da532c"

    [params.search]
        enable = true
        type = 'algolia'
        contentLength = 4000
        placeholder = ''
        maxResultLength = 10
        snippetLength = 30
        highlightTag = 'em'
        absoluteURL = false

        [params.search.algolia]
            index = ''
            appID = ''
            searchKey = ''

    [params.page]
        hiddenFromHomePage = false
        hiddenFromSearch = false
        twemoji = false
        lightgallery = false
        ruby = true
        fraction = true
        fontawesome = true
        linkToMarkdown = true
        rssFullText = false
    
        [params.page.toc]
            enable = true
            keepStatic = false
            auto = true

        [params.page.code]
            copy = true
            maxShownLines = 50
    
        [params.page.math]
            enable = false
            inlineLeftDelimiter = ""
            inlineRightDelimiter = ""
            blockLeftDelimiter = ""
            blockRightDelimiter = ""
            copyTex = true
            mhchem = true

        [params.page.mapbox]
            accessToken = "pk.eyJ1IjoiZGlsbG9uenEiLCJhIjoiY2s2czd2M2x3MDA0NjNmcGxmcjVrZmc2cyJ9.aSjv2BNuZUfARvxRYjSVZQ"
            lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
            darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
            navigation = true
            geolocate = true
            scale = true
            fullscreen = true

        [params.page.share]
            enable = false
            Twitter = true
            Facebook = true
            Linkedin = false
            Whatsapp = false
            Pinterest = false
            Tumblr = false
            HackerNews = true
            Reddit = false
            VK = false
            Buffer = false
            Xing = false
            Line = true
            Instapaper = false
            Pocket = false
            Flipboard = false
            Weibo = true
            Blogger = false
            Baidu = false
            Odnoklassniki = false
            Evernote = false
            Skype = false
            Trello = false
            Mix = false

    [params.cookieconsent]
        enable = false

        [params.cookieconsent.content]
            message = ''
            dismiss = ''
            link = ''

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = true
        lineNumbersInTable = true
        noClasses = false
  
    [markup.goldmark]
        [markup.goldmark.extensions]
            definitionList = true
            footnote = true
            linkify = true
            strikethrough = true
            table = true
            taskList = true
            typographer = true

    [markup.goldmark.renderer]
        unsafe = true
  
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6

[sitemap]
    changefreq = "weekly"
    filename = "sitemap.xml"
    priority = 0.5

[permalinks]
    posts = ":filename"

[mediaTypes]
    [mediaTypes."text/plain"]
        suffixes = ["md"]

[outputFormats.MarkDown]
    mediaType = "text/plain"
    isPlainText = true
    isHTML = false

[outputs]
    home = ["HTML", "RSS", "JSON"]
    page = ["HTML", "MarkDown"]
    section = ["HTML", "RSS"]
    taxonomy = ["HTML", "RSS"]
    taxonomyTerm = ["HTML"]